title: "rmbezo"
author: "Roman"
email: your@email.com
description: >-
  Notes on engineering, systems, and code.
baseurl: ""
url: "https://rmbezo.github.io"
github_username: rmbezo

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
